export const TAGS_MOCK = [
  {
    id: '508',
    name: '\tmalware_classification:malware-category="Botnet"',
    colour: '#22681c',
    exportable: false,
    org_id: '2',
    user_id: '1',
    hide_tag: true,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: true,
    favourite: false,
    count: 4,
    attribute_count: 1
  },
  {
    id: '423',
    name: ' C2',
    colour: '#c1e21c',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 29
  },
  {
    id: '458',
    name: ' Cobalt Strike Beacon',
    colour: '#3b9989',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 1
  },
  {
    id: '452',
    name: ' DLL Dropper',
    colour: '#9edf47',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 10
  },
  {
    id: '455',
    name: ' Decoy',
    colour: '#82b37e',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 1
  },
  {
    id: '456',
    name: ' Doc(x)',
    colour: '#8bfe8c',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 2
  },
  {
    id: '451',
    name: ' Download',
    colour: '#49f1ed',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 11
  },
  {
    id: '542',
    name: ' Flash',
    colour: '#160940',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 1
  },
  {
    id: '963',
    name: ' Malicious Batch Script',
    colour: '#3d7a00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '966',
    name: ' Ransomware',
    colour: '#ffd890',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '419',
    name: ' Smoke Loader',
    colour: '#3d7a00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 3
  },
  {
    id: '964',
    name: ' VBS Downloader',
    colour: '#3d7a00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '792',
    name: '"Lingarder Limited"',
    colour: '#e8ece2',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '669',
    name: '.kz Domain',
    colour: '#3f86b0',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '633',
    name: '10291029JSJUYNHG',
    colour: '#000000',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '568',
    name: 'ANEL',
    colour: '#700bfb',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '92',
    name: 'APT',
    colour: '#f71212',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 12,
    attribute_count: 0
  },
  {
    id: '666',
    name: 'ARTILDA CONSULTING LIMITED',
    colour: '#7f3e2d',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '594',
    name: 'Actor: APT28',
    colour: '#aa6c53',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '571',
    name: 'Actor: Lazarus',
    colour: '#e0b538',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '596',
    name: 'Actor: Sofacy',
    colour: '#671079',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '417',
    name: 'Adware',
    colour: '#42933e',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 2
  },
  {
    id: '889',
    name: 'Anchor',
    colour: '#000000',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '144',
    name: 'Android Malware',
    colour: '#211c1c',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 6,
    attribute_count: 0
  },
  {
    id: '595',
    name: 'Autoit',
    colour: '#ab875e',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '717',
    name: 'BR_CTI_Investigar',
    colour: '#ff0000',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '453',
    name: 'Backdoor',
    colour: '#197ff9',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 5
  },
  {
    id: '267',
    name: 'Banker',
    colour: '#f24722',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '631',
    name: 'Banker: Dridex',
    colour: '#6f236b',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '630',
    name: 'Banker: Gozi ISFB v2',
    colour: '#20ad13',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '611',
    name: 'Banker: TrickBot',
    colour: '#cdce6a',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 4,
    attribute_count: 0
  },
  {
    id: '402',
    name: 'Bokbot',
    colour: '#f02988',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '632',
    name: 'Botnet "3101"',
    colour: '#bcdb18',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '629',
    name: 'CERT-XLM:malicious-code="spyware-rat"',
    colour: '#5f0044',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: true,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '775',
    name: 'CERT-XLM:malicious-code="trojan-malware"',
    colour: '#5a0041',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: true,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '569',
    name: 'CHCHES',
    colour: '#8b6bca',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 27
  },
  {
    id: '457',
    name: 'Cobalt Strike',
    colour: '#0ab4a7',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 5,
    attribute_count: 10
  },
  {
    id: '605',
    name: 'Country: Pakistan',
    colour: '#b11b8a',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1370',
    name: 'DOTRUNPEX',
    colour: '#E08AB5',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '601',
    name: 'DPRK',
    colour: '#302c04',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '445',
    name: 'DROPPER DLLS',
    colour: '#195125',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 4
  },
  {
    id: '448',
    name: 'Decoy',
    colour: '#b2f8b2',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 1
  },
  {
    id: '1056',
    name: 'DescriptionTechnique',
    colour: '#00ae7a',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 2
  },
  {
    id: '665',
    name: 'Digital Signature',
    colour: '#f591da',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '424',
    name: 'Download',
    colour: '#56b352',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 20
  },
  {
    id: '597',
    name: 'Downloader',
    colour: '#0dcd05',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '109',
    name: 'Dridex',
    colour: '#ab022a',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 14
  },
  {
    id: '934',
    name: 'Emotet',
    colour: '#4de3bf',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '786',
    name: 'FindPOS',
    colour: '#0235a3',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '787',
    name: 'FindStr',
    colour: '#62459e',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '406',
    name: 'IcedID',
    colour: '#16f5f5',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1138',
    name: 'Intel 471:GIR="1.2.2 - Ransomware-as-a-Service (RaaS)"',
    colour: '#1f2325',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '604',
    name: 'Keylogger',
    colour: '#2be799',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '1371',
    name: 'Loader',
    colour: '#BFC5AA',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '985',
    name: 'Lokibot',
    colour: '#6ed8f0',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 1
  },
  {
    id: '215',
    name: 'MalSpam',
    colour: '#700cf0',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '429',
    name: 'Malvertising',
    colour: '#777174',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 18
  },
  {
    id: '602',
    name: 'Malware: PowerRatankba,b',
    colour: '#403c80',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '598',
    name: 'Malware: Zebrocy',
    colour: '#89a9b6',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '790',
    name: 'Memory Scraper',
    colour: '#0dd733',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '970',
    name: 'Mirai',
    colour: '#ff0000',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '71',
    name: 'OSINT',
    colour: '#ffffff',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 29,
    attribute_count: 3
  },
  {
    id: '1120',
    name: 'PAP:CLEAR',
    colour: '#ffffff',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '186',
    name: 'PAP:WHITE',
    colour: '#80ff00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 2
  },
  {
    id: '447',
    name: 'PDF',
    colour: '#888f83',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '425',
    name: 'Panda Banker',
    colour: '#36a013',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 1
  },
  {
    id: '468',
    name: 'PasteBin: MALWAREMESSIAGH',
    colour: '#ab34e3',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '449',
    name: 'Payload',
    colour: '#cb57f8',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 2
  },
  {
    id: '222',
    name: 'Phishing',
    colour: '#856c13',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '785',
    name: 'PoSeidon',
    colour: '#7bd107',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '788',
    name: 'Point-of-Sale',
    colour: '#37d4e6',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '573',
    name: 'PowerRatankba',
    colour: '#7a0e9f',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '603',
    name: 'PowerShell Installer',
    colour: '#7036f2',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '968',
    name: 'PowerView',
    colour: '#6772d6',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 1
  },
  {
    id: '454',
    name: 'Powershell',
    colour: '#2133c6',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 2
  },
  {
    id: '933',
    name: 'Powershell Empire',
    colour: '#10e874',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 140
  },
  {
    id: '998',
    name: 'PyXie',
    colour: '#db00c5',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 8
  },
  {
    id: '543',
    name: 'RAT',
    colour: '#540b39',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '789',
    name: 'RAWINPUT',
    colour: '#787ad7',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '566',
    name: 'REDLEAVES',
    colour: '#84cd7f',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 17
  },
  {
    id: '443',
    name: 'RTF',
    colour: '#882d0e',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 8
  },
  {
    id: '953',
    name: 'Ransomware',
    colour: '#000000',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 5,
    attribute_count: 0
  },
  {
    id: '978',
    name: 'Remcos RAT',
    colour: '#595757',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '572',
    name: 'Ruse: Job Application',
    colour: '#421b85',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '993',
    name: 'Ryuk',
    colour: '#c311f0',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '446',
    name: 'SCRIPTLET',
    colour: '#1ae080',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 4
  },
  {
    id: '378',
    name: 'SMB',
    colour: '#000000',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 6
  },
  {
    id: '791',
    name: 'Signed',
    colour: '#3b947c',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '932',
    name: 'Source:Urlscan.io',
    colour: '#ff8a00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '450',
    name: 'Stage 1',
    colour: '#5fb4b2',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 30
  },
  {
    id: '485',
    name: 'Stage 2',
    colour: '#fccc51',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 6
  },
  {
    id: '224',
    name: 'Stantinko',
    colour: '#a9b7b8',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '202',
    name: 'Symantec',
    colour: '#ef1515',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '664',
    name: 'TerraLoader',
    colour: '#b5654e',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '793',
    name: 'Thawte',
    colour: '#2ac804',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '218',
    name: 'Threat Source:OSINT',
    colour: '#009922',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '291',
    name: 'Threat Type:APT',
    colour: '#0f4d00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '169',
    name: 'Threat Type:RAT',
    colour: '#1f9900',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '81',
    name: 'Threat:Sofacy/APT28',
    colour: '#f1ee1d',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 6,
    attribute_count: 0
  },
  {
    id: '200',
    name: 'Trj=Doublepulsar',
    colour: '#00fff3',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '567',
    name: 'UPPERCUT',
    colour: '#94fdc4',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '995',
    name: 'Ursnif',
    colour: '#bd8c8c',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 20
  },
  {
    id: '409',
    name: 'VT:More than 10 URLs detected',
    colour: '#e82e45',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 1
  },
  {
    id: '794',
    name: 'Version 15.10',
    colour: '#ef7f5c',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '612',
    name: 'Version: 1057',
    colour: '#3e9874',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '444',
    name: 'Word Doc(x)',
    colour: '#b2f9b1',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '544',
    name: 'Zero Day',
    colour: '#cb58ae',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 1
  },
  {
    id: '96',
    name: 'admiralty-scale:information-credibility="1"',
    colour: '#0eb100',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 4,
    attribute_count: 0
  },
  {
    id: '82',
    name: 'admiralty-scale:information-credibility="2"',
    colour: '#0fc000',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 13,
    attribute_count: 1
  },
  {
    id: '64',
    name: 'admiralty-scale:information-credibility="3"',
    colour: '#11d000',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 7,
    attribute_count: 3
  },
  {
    id: '85',
    name: 'admiralty-scale:information-credibility="6"',
    colour: '#14ff00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 2
  },
  {
    id: '1114',
    name: 'admiralty-scale:source-reliability="a"',
    colour: '#054300',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '74',
    name: 'admiralty-scale:source-reliability="b"',
    colour: '#075200',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 12,
    attribute_count: 62
  },
  {
    id: '63',
    name: 'admiralty-scale:source-reliability="c"',
    colour: '#086200',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 4,
    attribute_count: 4
  },
  {
    id: '87',
    name: 'admiralty-scale:source-reliability="f"',
    colour: '#0c9100',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 5,
    attribute_count: 5
  },
  {
    id: '657',
    name: 'adversary:infrastructure-action="take-down"',
    colour: '#410069',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '173',
    name: 'adversary:infrastructure-state="active"',
    colour: '#62009e',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 1
  },
  {
    id: '160',
    name: 'adversary:infrastructure-status="compromised"',
    colour: '#2d0048',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 156
  },
  {
    id: '382',
    name: 'adversary:infrastructure-type="exploit-distribution-point"',
    colour: '#8300d4',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '132',
    name: 'adversary:infrastructure-type="panel"',
    colour: '#9100ea',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 3
  },
  {
    id: '166',
    name: 'adversary:infrastructure-type="proxy"',
    colour: '#7600bf',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 1
  },
  {
    id: '172',
    name: 'adversary:infrastructure-type="unknown"',
    colour: '#7000b4',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 1
  },
  {
    id: '982',
    name: 'attack-pattern:name="password brute forcing"',
    colour: '#3F63AD',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1463',
    name: 'bitte geh',
    colour: '#ffffff',
    exportable: true,
    org_id: '12345',
    user_id: '12345',
    hide_tag: false,
    numerical_value: '12345',
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: true,
    favourite: false,
    count: 0,
    attribute_count: 0
  },
  {
    id: '1236',
    name: 'cccs:malware_classification="webshell"',
    colour: '#4c3011',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 30
  },
  {
    id: '1118',
    name: 'cert-fr:fiabilite="Bonne"',
    colour: '#00714f',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '439',
    name: 'cert-ist:enriched',
    colour: '#fea700',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '440',
    name: 'cert-ist:ioc_accuracy="high"',
    colour: '#392500',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '714',
    name: 'cert-ist:ioc_accuracy="medium"',
    colour: '#372500',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '987',
    name: 'cert-ist:malware_type="Keylogger"',
    colour: '#764e00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '986',
    name: 'cert-ist:malware_type="Stealer"',
    colour: '#815500',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1237',
    name: 'cert-ist:malware_type="Webshell"',
    colour: '#825600',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 30
  },
  {
    id: '441',
    name: 'cert-ist:threat_level="low"',
    colour: '#3a2600',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '715',
    name: 'cert-ist:threat_level="medium"',
    colour: '#3c2700',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '713',
    name: 'cert-ist:threat_targeted_region="Western Europe"',
    colour: '#e49600',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '711',
    name: 'cert-ist:threat_targeted_sector="Academic and Research"',
    colour: '#9d6800',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '438',
    name: 'cert-ist:threat_targeted_sector="Finance"',
    colour: '#885a00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '712',
    name: 'cert-ist:threat_targeted_sector="Gov"',
    colour: '#986400',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '437',
    name: 'cert-ist:threat_targeted_system="Windows"',
    colour: '#4d3300',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '442',
    name: 'cert-ist:threat_type="apt"',
    colour: '#f8a400',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '991',
    name: 'cert-ist:threat_type="malware_outbreak"',
    colour: '#f6a300',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '236',
    name: 'certsi:critical-sector="energy"',
    colour: '#ff8e41',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '329',
    name: 'circl:incident-classification="cryptojacking"',
    colour: '#51a200',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '179',
    name: 'circl:incident-classification="information-leak"',
    colour: '#4b9600',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '59',
    name: 'circl:incident-classification="malware"',
    colour: '#3a7300',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 203,
    attribute_count: 1
  },
  {
    id: '86',
    name: 'circl:incident-classification="phishing"',
    colour: '#316200',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 7,
    attribute_count: 0
  },
  {
    id: '185',
    name: 'circl:incident-classification="scam"',
    colour: '#4e9c00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 5,
    attribute_count: 0
  },
  {
    id: '227',
    name: 'circl:incident-classification="spam"',
    colour: '#1c3900',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '68',
    name: 'circl:incident-classification="system-compromise"',
    colour: '#1f3f00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 7,
    attribute_count: 0
  },
  {
    id: '198',
    name: 'circl:incident-classification="vulnerability"',
    colour: '#3f7f00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 3
  },
  {
    id: '66',
    name: 'circl:topic="finance"',
    colour: '#6bd600',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 34,
    attribute_count: 0
  },
  {
    id: '67',
    name: 'circl:topic="ict"',
    colour: '#6edc00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '259',
    name: 'circl:topic="industry"',
    colour: '#74e800',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '72',
    name: 'circl:topic="services"',
    colour: '#7af300',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '887',
    name: 'collaborative-intelligence:request="historical-information"',
    colour: '#c5003b',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '518',
    name: 'collaborative-intelligence:request="more-samples"',
    colour: '#6d0021',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1097',
    name: 'collaborative-intelligence:request="related-samples"',
    colour: '#7c0025',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '317',
    name: 'collaborative-intelligence:request="sample"',
    colour: '#420014',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '613',
    name: 'core-parser.dll',
    colour: '#54cc21',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1117',
    name: 'cossi:RechercheSourceOuverte="Autorisee"',
    colour: '#008e63',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '1116',
    name: 'cossi:TLP="white"',
    colour: '#ffffff',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '1057',
    name: 'cossi:fiabilite="Bonne"',
    colour: '#00714f',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 4
  },
  {
    id: '333',
    name: 'cyber-threat-framework:Effect/Consequence="destroy-hardware-software-or-data"',
    colour: '#00ffb3',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 1
  },
  {
    id: '334',
    name: 'cyber-threat-framework:Engagement="exploit-vulnerabilities"',
    colour: '#008960',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 1
  },
  {
    id: '1067',
    name: 'cycat:scope="detection"',
    colour: '#0fbf00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 1
  },
  {
    id: '1027',
    name: 'cycat:scope="investigation"',
    colour: '#13f200',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1026',
    name: 'cycat:type="fingerprint"',
    colour: '#0c9900',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '511',
    name: 'ddos:type="amplification-attack"',
    colour: '#285c00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '688',
    name: 'ddos:type="flooding-attack"',
    colour: '#5ed600',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '366',
    name: 'diamond-model:Adversary',
    colour: '#662500',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 2
  },
  {
    id: '365',
    name: 'diamond-model:Capability',
    colour: '#993700',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 153
  },
  {
    id: '363',
    name: 'diamond-model:Infrastructure',
    colour: '#cc4900',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 280
  },
  {
    id: '208',
    name: 'dnc:infrastructure-type="exploit-kit"',
    colour: '#ff0000',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '316',
    name: 'dnc:malware-type="CoinMiner"',
    colour: '#a0a300',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 4,
    attribute_count: 0
  },
  {
    id: '115',
    name: 'dnc:malware-type="Ransomware"',
    colour: '#000000',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 6,
    attribute_count: 0
  },
  {
    id: '122',
    name: 'ecsirt:availability="ddos"',
    colour: '#00bdbd',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '223',
    name: 'ecsirt:fraud="phishing"',
    colour: '#00e7e7',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '538',
    name: 'ecsirt:intrusions="application-compromise"',
    colour: '#00a0a0',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '621',
    name: 'ecsirt:intrusions="backdoor"',
    colour: '#00b3b3',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 7,
    attribute_count: 0
  },
  {
    id: '586',
    name: 'ecsirt:intrusions="compromised"',
    colour: '#00aeae',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '641',
    name: 'ecsirt:malicious-code="c&c"',
    colour: '#007575',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 13
  },
  {
    id: '79',
    name: 'ecsirt:malicious-code="malware"',
    colour: '#006262',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 8,
    attribute_count: 0
  },
  {
    id: '65',
    name: 'ecsirt:malicious-code="ransomware"',
    colour: '#006c6c',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 90,
    attribute_count: 0
  },
  {
    id: '591',
    name: 'ecsirt:malicious-code="trojan"',
    colour: '#004f4f',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '967',
    name: 'emotet:epoch="1"',
    colour: '#cd05ff',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 1
  },
  {
    id: '142',
    name: 'enisa:nefarious-activity-abuse="DNS-poisoning-or-DNS-spoofing-or-DNS-Manipulations"',
    colour: '#44d400',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '125',
    name: 'enisa:nefarious-activity-abuse="exploits-exploit-kits"',
    colour: '#3ab400',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '143',
    name: 'enisa:nefarious-activity-abuse="infected-trusted-mobile-apps"',
    colour: '#37ac00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '121',
    name: 'enisa:nefarious-activity-abuse="mobile-malware"',
    colour: '#37ab00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 8,
    attribute_count: 2
  },
  {
    id: '116',
    name: 'enisa:nefarious-activity-abuse="ransomware"',
    colour: '#39b300',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 12,
    attribute_count: 0
  },
  {
    id: '114',
    name: 'enisa:nefarious-activity-abuse="remote-access-tool"',
    colour: '#4bec00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 8,
    attribute_count: 0
  },
  {
    id: '514',
    name: 'enisa:nefarious-activity-abuse="spear-phishing-attacks"',
    colour: '#3bb800',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '476',
    name: 'estimative-language:confidence-in-analytic-judgment="high"',
    colour: '#0029ff',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 13,
    attribute_count: 0
  },
  {
    id: '505',
    name: 'estimative-language:confidence-in-analytic-judgment="low"',
    colour: '#0022d6',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '331',
    name: 'estimative-language:confidence-in-analytic-judgment="moderate"',
    colour: '#0026eb',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 14,
    attribute_count: 4
  },
  {
    id: '3',
    name: 'estimative-language:likelihood-probability="almost-certain"',
    colour: '#001fc2',
    exportable: true,
    org_id: '2',
    user_id: '0',
    hide_tag: false,
    numerical_value: '95',
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 13,
    attribute_count: 7
  },
  {
    id: '1',
    name: 'estimative-language:likelihood-probability="likely"',
    colour: '#001899',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: '55',
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 7
  },
  {
    id: '4',
    name: 'estimative-language:likelihood-probability="roughly-even-chance"',
    colour: '#001585',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: '45',
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: true,
    count: 7,
    attribute_count: 2
  },
  {
    id: '5',
    name: 'estimative-language:likelihood-probability="unlikely"',
    colour: '#001270',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: '20',
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 0
  },
  {
    id: '2',
    name: 'estimative-language:likelihood-probability="very-likely"',
    colour: '#001cad',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: '80',
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 14,
    attribute_count: 12
  },
  {
    id: '648',
    name: 'europol-event:c&c-server-hosting',
    colour: '#000745',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 13
  },
  {
    id: '237',
    name: 'europol-event:hosting-phishing-sites',
    colour: '#000e87',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '123',
    name: 'europol-incident:availability="dos-ddos"',
    colour: '#000a64',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '587',
    name: 'europol-incident:information-security="unauthorized-access"',
    colour: '#0013bb',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '588',
    name: 'europol-incident:information-security="unauthorized-modification"',
    colour: '#0014c5',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '642',
    name: 'europol-incident:malware="c&c"',
    colour: '#000850',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 13
  },
  {
    id: '98',
    name: 'expansion:whois-registrant-email',
    colour: '#1eed40',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1372',
    name: 'feedly:source="Sekoia.io Blog"',
    colour: '#a00919',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1115',
    name: 'fr-classif:non-classifiees="NON-CLASSIFIEES"',
    colour: '#ff1f00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '55',
    name: 'hau de gang nei',
    colour: '#cc3398',
    exportable: true,
    org_id: '2',
    user_id: '0',
    hide_tag: true,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: true,
    favourite: true,
    count: 0,
    attribute_count: 0
  },
  {
    id: '752',
    name: 'honeypot-basic:containment="block"',
    colour: '#009e6f',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '751',
    name: 'honeypot-basic:data-capture="attacks"',
    colour: '#00815a',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1002',
    name: 'inthreat:event-src="feed-osint"',
    colour: '#DADCF0',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '972',
    name: 'keylogger/infostealer',
    colour: '#bd472d',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '974',
    name: 'kill-chain:Actions on Objectives',
    colour: '#ff00b8',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 2
  },
  {
    id: '646',
    name: 'kill-chain:Command and Control',
    colour: '#e200a3',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 347
  },
  {
    id: '380',
    name: 'kill-chain:Delivery',
    colour: '#8a0064',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 89
  },
  {
    id: '372',
    name: 'kill-chain:Installation',
    colour: '#c5008e',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 31
  },
  {
    id: '975',
    name: 'kill-chain:Reconnaissance',
    colour: '#50003a',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1161',
    name: 'maec-malware-behavior:maec-malware-behavior="mine-for-cryptocurrency"',
    colour: '#b00074',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '647',
    name: 'maec-malware-capabilities:maec-malware-capability="command-and-control"',
    colour: '#480004',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 13
  },
  {
    id: '981',
    name: 'maec-malware-capabilities:maec-malware-capability="machine-access-control"',
    colour: '#5f0006',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '969',
    name: 'maldoc',
    colour: '#bf0dcc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '965',
    name: 'malware:emotet',
    colour: '#ad00ff',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '242',
    name: 'malware_classification:malware-category="Botnet"',
    colour: '#22681c',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 14,
    attribute_count: 0
  },
  {
    id: '1373',
    name: 'malware_classification:malware-category="Downloader"',
    colour: '#345d00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '62',
    name: 'malware_classification:malware-category="Ransomware"',
    colour: '#2c4f00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 99,
    attribute_count: 13
  },
  {
    id: '107',
    name: 'malware_classification:malware-category="Rootkit"',
    colour: '#305600',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '69',
    name: 'malware_classification:malware-category="Spyware"',
    colour: '#3c6b00',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '205',
    name: 'malware_classification:malware-category="Trojan"',
    colour: '#284800',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 9,
    attribute_count: 0
  },
  {
    id: '1240',
    name: 'malware_classification:memory-classification="user-process"',
    colour: '#8bf800',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '195',
    name: 'malware_classification:obfuscation-technique="tunneling"',
    colour: '#5ca400',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '176',
    name: 'malware_classification:payload-classification="dropper"',
    colour: '#77d500',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: false,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 19
  },
  {
    id: '13',
    name: 'misp-galaxy:360net-threat-actor="CIA - APT-C-39"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1453',
    name: 'misp-galaxy:360net-threat-actor="Gamaredon - APT-C-53"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '54',
    name: 'misp-galaxy:360net-threat-actor="摩诃草 - APT-C-09"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 1
  },
  {
    id: '1450',
    name: 'misp-galaxy:360net-threat-actor="海莲花 - APT-C-00"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '1098',
    name: 'misp-galaxy:amitt-misinformation-pattern="Create Master Narratives"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1030',
    name: 'misp-galaxy:amitt-misinformation-pattern="Create fake Social Media Profiles / Pages / Groups"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1101',
    name: 'misp-galaxy:amitt-misinformation-pattern="Create fake websites"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1099',
    name: 'misp-galaxy:amitt-misinformation-pattern="Facilitate State Propaganda"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1102',
    name: 'misp-galaxy:amitt-misinformation-pattern="Legacy web content"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1100',
    name: 'misp-galaxy:amitt-misinformation-pattern="Search Engine Optimization"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1451',
    name: 'misp-galaxy:ammunitions="Fiocchi 12 Gauge Ammo #7 - 250 Rounds of 1 oz. #7"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1457',
    name: 'misp-galaxy:ammunitions="Fiocchi 12 Gauge Ammo #8 - 250 Rounds of 1 oz. #8 Shot (Lead) Ammunition"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1456',
    name: 'misp-galaxy:ammunitions="Fiocchi 12 Gauge Ammo - 250 Rounds of 2"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1458',
    name: 'misp-galaxy:ammunitions="Fiocchi 16 Gauge  Ammo - 25 Rounds of 1 oz. #8 Shot (Lead) Ammunition"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '12',
    name: 'misp-galaxy:ammunitions="Fiocchi 22 LR  Ammo - 50 Rounds of 38 Grain CPHP Ammunition"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '6',
    name: 'misp-galaxy:ammunitions="Fiocchi 32 ACP Ammo - 1000 Rounds of 73 Grain FMJ Ammunition"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1452',
    name: 'misp-galaxy:ammunitions="Fiocchi Target Shooting Dynamics 12 Gauge  Ammo - 250 Rounds of 1 oz. #7"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1449',
    name: 'misp-galaxy:ammunitions="Fiocchi White Rino 12 Gauge  Ammo - 250 Rounds of 2"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '765',
    name: 'misp-galaxy:android="Adwind"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '988',
    name: 'misp-galaxy:android="LokiBot"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '250',
    name: 'misp-galaxy:android="Tizi"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '1454',
    name: 'misp-galaxy:atrm="AZT302.3 - Automation Account Runbook Managed Identity"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1455',
    name: 'misp-galaxy:atrm="AZT404.4 - App Service"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1331',
    name: 'misp-galaxy:backdoor="BIGRAISIN"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '1337',
    name: 'misp-galaxy:backdoor="FASTFIRE"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '1344',
    name: 'misp-galaxy:backdoor="GRAYZONE"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '1345',
    name: 'misp-galaxy:backdoor="HANGMAN.V2"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '1351',
    name: 'misp-galaxy:backdoor="LOGCABIN"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '1289',
    name: 'misp-galaxy:backdoor="POOLRAT"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1359',
    name: 'misp-galaxy:backdoor="SOURDOUGH"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '582',
    name: 'misp-galaxy:backdoor="ServHelper"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1361',
    name: 'misp-galaxy:backdoor="TROIBOMB"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 3
  },
  {
    id: '1295',
    name: 'misp-galaxy:backdoor="VEILEDSIGNAL"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '635',
    name: 'misp-galaxy:banker="DanaBot"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '288',
    name: 'misp-galaxy:banker="Dok"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '266',
    name: 'misp-galaxy:banker="Geodo"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 4,
    attribute_count: 0
  },
  {
    id: '469',
    name: 'misp-galaxy:banker="Gozi"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '337',
    name: 'misp-galaxy:banker="IcedID"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '428',
    name: 'misp-galaxy:banker="Kronos"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '264',
    name: 'misp-galaxy:banker="Panda Banker"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 6,
    attribute_count: 0
  },
  {
    id: '361',
    name: 'misp-galaxy:banker="Trickbot"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 4,
    attribute_count: 0
  },
  {
    id: '460',
    name: 'misp-galaxy:botnet="BetaBot"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1167',
    name: 'misp-galaxy:botnet="Dark.IoT"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '497',
    name: 'misp-galaxy:botnet="Gafgyt"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '776',
    name: 'misp-galaxy:botnet="Hide and Seek"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '495',
    name: 'misp-galaxy:botnet="Mirai"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 6,
    attribute_count: 0
  },
  {
    id: '950',
    name: 'misp-galaxy:botnet="Muhstik"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '509',
    name: 'misp-galaxy:botnet="Persirai"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1460',
    name: 'misp-galaxy:cmtmf-attack-pattern="Exploit via Radio Interfaces"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '56',
    name: 'misp-galaxy:cmtmf-attack-pattern="Replication Through IP"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 0
  },
  {
    id: '10',
    name: 'misp-galaxy:cmtmf-attack-pattern="URI Hijacking"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '1155',
    name: 'misp-galaxy:country="cameroon"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1134',
    name: 'misp-galaxy:country="china"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1096',
    name: 'misp-galaxy:country="iran"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 2,
    attribute_count: 0
  },
  {
    id: '1446',
    name: 'misp-galaxy:country="israel"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1156',
    name: 'misp-galaxy:country="ivory coast"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1157',
    name: 'misp-galaxy:country="morocco"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1188',
    name: 'misp-galaxy:country="netherlands"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 1
  },
  {
    id: '1144',
    name: 'misp-galaxy:country="north korea"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1103',
    name: 'misp-galaxy:country="russia"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 3,
    attribute_count: 0
  },
  {
    id: '1158',
    name: 'misp-galaxy:country="senegal"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1159',
    name: 'misp-galaxy:country="togo"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1187',
    name: 'misp-galaxy:country="united states"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 0,
    attribute_count: 4
  },
  {
    id: '867',
    name: 'misp-galaxy:course-of-action="Credential Dumping Mitigation"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '866',
    name: 'misp-galaxy:course-of-action="Network Sniffing Mitigation"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '865',
    name: 'misp-galaxy:course-of-action="PowerShell Mitigation"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '1166',
    name: 'misp-galaxy:cryptominers="Hezb"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  },
  {
    id: '206',
    name: 'misp-galaxy:exploit-kit="Astrum"',
    colour: '#0088cc',
    exportable: true,
    org_id: '0',
    user_id: '0',
    hide_tag: false,
    numerical_value: null,
    is_galaxy: true,
    is_custom_galaxy: false,
    local_only: false,
    favourite: false,
    count: 1,
    attribute_count: 0
  }
];
