# Note: Don't change docs_dir or site_dir, that would break CI
site_name: MMISP Frontend Qualitätssicherungsbericht
repo_url: https://gitlab.kit.edu/kit/kit-cert/mmisp/frontend
site_author: MMISP Frontend Team

theme:
  name: 'material'

nav:
  - intro.md
  - test_cases.md
  - bugs.md

plugins:
  - search
  - with-pdf:
      # See https://github.com/orzih/mkdocs-with-pdf
      cover_subtitle: Qualitätssicherungsphase
      # NOTE: There's a zero width space in these parentheses because I couldn't make the copyright not show up otherwise.
      #       It's also possible to use custom templates with mkdocs-with-pdf, might be worth it, see github linked above.
      copyright: '​'
