<script lang="ts">
    import type { PageData } from './$types';
    
    import DynTable from '$lib/components/table/dynTable/DynTable.svelte';
  
    /**
     * Page data containing the data of the event with the id in the url
     */
    export let data: PageData;
  </script>
  
  <!-- 
    @component
    This Page will display the event with a {@link DynCard} component. The header will be generated by the formHeaders depending on the mode. 
  
    The Galaxies and Tags will be displayed with a {@link PillCollection}.
    The EventGraph will be displayed with the {@link EventGraph} component.
    The Attributes are basically a {@link DynTable}
  
    The update of the event will be handled by a form inside of this page, that is a wrapper around some DynCards. Therefore the "name" from from any inputted component will be used to calculate the final object we will send to the server. 
   -->
  
  <div class="h-full overflow-auto">
    <section>
      <h1>Attributes</h1>
      <DynTable data={[]} header={[]} />
    </section>
  
  </div>
  
  <style>
    .g {
      grid: 50rem 50rem / 1fr 1fr;
    }
  </style>