<script lang="ts">
  import DynCard from '$lib/components/card/dynCard/DynCard.svelte';
  import type { PageData } from './$types';
  import EditMode from './EditMode.svelte';

  import AddTagForm from '$lib/components/tagForms/AddTagForm.svelte';
  import type { PickerPill } from '$lib/models/Picker.interface';
  import EventTags from './EventTags.svelte';
  import { header } from './formHeaders';
  import DynTable from '$lib/components/table/dynTable/DynTable.svelte';

  /**
   * Page data containing the data of the event with the id in the url
   */
  export let data: PageData;

  let addTag = false;

  /**
   * The currently selected pills
   */
  let selection: PickerPill[] = [];
</script>

<!-- 
  @component
  This Page will display the event with a {@link DynCard} component. The header will be generated by the formHeaders depending on the mode. 

  The Galaxies and Tags will be displayed with a {@link PillCollection}.
  The EventGraph will be displayed with the {@link EventGraph} component.
  The Attributes are basically a {@link DynTable}

  The update of the event will be handled by a form inside of this page, that is a wrapper around some DynCards. Therefore the "name" from from any inputted component will be used to calculate the final object we will send to the server. 
 -->

<div class="h-full overflow-auto">
  <EditMode>
    <div class="grid h-full grid-cols-2 gap-2 lg:flex-nowrap">
      {#if addTag}
        <AddTagForm bind:selection />
      {:else}
        <section class="h-full">
          <DynCard data={data.event} {header} />
        </section>
      {/if}
      <section class="h-full">
        <EventTags bind:addTag {data} bind:selection />
      </section>
    </div>
  </EditMode>
  <section>
    <h1>Attributes</h1>
    <DynTable data={[]} header={[]} />
  </section>
</div>
