<script lang="ts">
  import DynCard from '$lib/components/card/dynCard/DynCard.svelte';
  import type { PageData } from './$types';
  import EditMode from './EditMode.svelte';

  import AddTagForm from '$lib/components/addTagForm/AddTagForm.svelte';
  import EventTags from './EventTags.svelte';
  import { header } from './formHeaders';
  import EventGraph from '$lib/components/eventGraph/EventGraph.svelte';
  import DynTable from '$lib/components/table/dynTable/DynTable.svelte';

  import Card from '$lib/components/card/Card.svelte';
  import PillCollection from '$lib/components/pills/pillCollection/PillCollection.svelte';

  /**
   * Page data containing the data of the event with the id in the url
   */
  export let data: PageData;

  let addTag = false;
</script>

<!-- 
  @component
  This Page will display the event with a {@link DynCard} component. The header will be generated by the formHeaders depending on the mode. 

  The Galaxies and Tags will be displayed with a {@link PillCollection}.
  The EventGraph will be displayed with the {@link EventGraph} component.
  The Attributes are basically a {@link DynTable}

  The update of the event will be handled by a form inside of this page, that is a wrapper around some DynCards. Therefore the "name" from from any inputted component will be used to calculate the final object we will send to the server. 
 -->

<div class="h-full overflow-auto">
  <EditMode>
    <div class="grid gap-2 g lg:flex-nowrap">
      {#if addTag}
        <AddTagForm />
      {:else}
        <section class="h-full">
          <DynCard data={data.event} {header} />
        </section>
      {/if}
      <section class="h-full">
        <EventTags bind:addTag {data} />
      </section>

      <section class="h-full">
        <Card class="h-full ">
          {#each data.event?.Galaxy ?? [] as galaxy}
            <div>
              <h1 class="text-xl text-center text-sky text-bold">{galaxy.name}</h1>
              <hr />
              <br />
              <PillCollection
                pills={galaxy.GalaxyCluster
                  ? galaxy.GalaxyCluster.map((y) => ({
                      icon: y.local ? 'mdi:cloud-off-outline' : 'mdi:earth',
                      label: y.relationship_type ? y.relationship_type : undefined,
                      text: y.value
                    }))
                  : []}
              />
            </div>
          {/each}
        </Card>
      </section>
    </div>
  </EditMode>
  <section>
    <h1>Attributes</h1>
    <DynTable data={[]} header={[]} />
  </section>

  <EventGraph event={data.event} />
</div>

<style>
  .g {
    grid: 50rem 50rem / 1fr 1fr;
  }
</style>
