@startuml
set separator ::
skinparam groupInheritance 5
skinparam defaultFontName Cantarell
skinparam packageStyle Rectangle
skinparam class {
  BackgroundColor<<Component>> #f6f2ff
  BackgroundColor<<ErrorPage>> #edd1e1
  BackgroundColor<<Layout>> #f8ffe5
  BackgroundColor<<Page>> #fff0e5
}
class "Button" as src/lib/components/button/Button.svelte.ts << (C, #9977DD) Component >> {
  __ Properties __
  +class?: <color:#DF8E1D><i> </i></color><color:#8839EF>string</color>
  __ Slots __
  +default
  __ Events __
  +click: <color:#DF8E1D><i> MouseEvent</i></color>
}
@enduml