variables:
  CI_DEBUG_SERVICES: 'true'

stages:
  - build_image
  - pre-build
  - build
  - test
  - deploy

default:
  tags:
    - kgr1-instance-standard
  image:
    name: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_node:${CI_COMMIT_SHA}
  interruptible: true

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "docs"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  auto_cancel:
    on_new_commit: interruptible

# build image stage

build_image_node:
  needs: []
  before_script: []
  stage: build_image
  tags:
    - kgr1-instance-standard
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >-
      echo '{"auths":{"https://registry.cert.kit.edu/v2/":{"auth": "'$(echo -n ${REGISTRY_USER}:${REGISTRY_PASSWORD} | base64 -w 0)'" }}}' > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.node"
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_node:${CI_COMMIT_BRANCH}
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_node:${CI_COMMIT_SHA}

build_image_nginx:
  needs:
    - build_image_node
  before_script: []
  stage: build_image
  tags:
    - kgr1-instance-standard
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >-
      echo '{"auths":{"https://registry.cert.kit.edu/v2/":{"auth": "'$(echo -n ${REGISTRY_USER}:${REGISTRY_PASSWORD} | base64 -w 0)'" }}}' > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.nginx"
      --build-arg fromimage=${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_node
      --build-arg fromtag=$CI_COMMIT_SHA
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_nginx:${CI_COMMIT_BRANCH}
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_nginx:${CI_COMMIT_SHA}

# === pre-build stage ===

#install_dependencies:
#  stage: pre-build
#  script:
#    - npm ci --cache .npm --prefer-offline
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}
#    paths:
#      - .npm/
#  artifacts:
#    expire_in: 1 day
#    paths:
#      - node_modules
#      - .svelte-kit
#  needs: []

# === build stage ===

docs:
  needs:
    - build_image_node
  stage: build
  trigger:
    include: .gitlab/docs.yml
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

# === test stage ===

unit_tests:
  needs:
    - build_image_node
  stage: test
  script:
    - cd /app
    - npx vitest run
  coverage: /All files[^|]*\|[^|]*\|\s+([\d\.]+)/
  artifacts:
    expire_in: 1 day
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

prettier:
  needs:
    - build_image_node
  stage: test
  script:
    - cd /app
    - npx prettier --check . "!misp-docker/**"

eslint:
  needs:
    - build_image_node
  stage: test
  script:
    - cd /app
    - npx eslint --format gitlab .
    - mv gl-code-quality-report.json $CI_PROJECT_DIR
  artifacts:
    expire_in: 1 day
    reports:
      codequality: gl-code-quality-report.json

svelte-check:
  needs:
    - build_image_node
  stage: test
  script:
    - cd /app
    - npm run check

integration_tests:
  tags:
    - beefy
    - any-image-allowed
  parallel: 2
  stage: test
  image:
    name: cypress/included:13.13.2
    entrypoint: ['']
  needs:
    - build_image_node
    - build_image_nginx
  services:
    - name: registry.cert.kit.edu/public-gitlab-ci/mysql-loader:latest
      alias: db
      variables:
        MYSQL_ROOT_PASSWORD: misp
        MYSQL_DUMP_FILE: /builds/${CI_PROJECT_PATH}/misp-docker-override/dump.sql
        MYSQL_DATABASE: misp
    - name: registry.cert.kit.edu/public-gitlab-ci/misp-core:latest
      alias: misp-core
      variables:
        MYSQL_PASSWORD: misp
        MYSQL_USER: root
        DISABLE_SSL_REDIRECT: true
        ENABLE_DB_SETTINGS: 'false'
        DEBUG: 1
    - name: valkey/valkey:7.2
      alias: redis
      variables:
        HEALTHCHECK_TCP_PORT: 6379
    - name: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_nginx:${CI_COMMIT_SHA}
      alias: frontend
      variables:
        NGINX_PORT: 81
        PUBLIC_MAINTENANCE_MODE: 'false'
        PUBLIC_MAINTENANCE_MESSAGE: Website is currently in maintenance mode. All editing is disabled.
        PUBLIC_REST_DISABLED: '{}'
        PUBLIC_REST_DISABLED_MESSAGE: The REST method you try to use is disabled
        PUBLIC_MISP_API_ENDPOINT: https://misp-core
        PUBLIC_DATE_FORMAT: yyyy-mm-DD
  script:
    # Create environment files
    - mv misp-docker-override/dump01.sql misp-docker-override/dump.sql
    - npm ci
    - cat cypress.env.template.json | sed "s/<your admin token>/${MISP01_AUTH_TOKEN}/" > cypress.env.json
    - sleep 900
    - npx cypress run --parallel --record --browser chrome --reporter junit --reporter-options mochaFile=reports/report-[hash].xml
  variables:
    CYPRESS_BASE_URL: http://frontend:81
    CYPRESS_VIDEO: 'true'
    ELECTRON_ENABLE_LOGGING: 'true'
  artifacts:
    expire_in: 1 day
    reports:
      junit: reports/report-*.xml
    expose_as: Cypress artifacts
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
