stages:
  - build_image
  - pre-build
  - build
  - test
  - deploy

default:
  tags:
    - any-image-allowed
    - concurrent
  image:
    name: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_node:${CI_COMMIT_SHA}
  interruptible: true

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "docs"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  auto_cancel:
    on_new_commit: interruptible

# build image stage
build_website:
  image: registry.cert.kit.edu/hub/library/node:24
  stage: build_image
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - build
  variables:
    KUBERNETES_MEMORY_REQUEST: '2Gi'
    KUBERNETES_MEMORY_LIMIT: '2Gi'

build_image_node:
  needs: []
  before_script: []
  stage: build_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >-
      echo '{"auths":{"https://registry.cert.kit.edu/v2/":{"auth": "'$(echo -n ${REGISTRY_USER}:${REGISTRY_PASSWORD} | base64 -w 0)'" }}}' > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.node"
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_node:${CI_COMMIT_BRANCH}
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_node:${CI_COMMIT_SHA}
  variables:
    KUBERNETES_MEMORY_REQUEST: '2Gi'
    KUBERNETES_MEMORY_LIMIT: '2Gi'

build_image_nginx:
  needs:
    - build_image_node
  before_script: []
  stage: build_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >-
      echo '{"auths":{"https://registry.cert.kit.edu/v2/":{"auth": "'$(echo -n ${REGISTRY_USER}:${REGISTRY_PASSWORD} | base64 -w 0)'" }}}' > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.nginx"
      --build-arg fromimage=${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_node
      --build-arg fromtag=$CI_COMMIT_SHA
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_nginx:${CI_COMMIT_BRANCH}
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_nginx:${CI_COMMIT_SHA}
  variables:
    KUBERNETES_MEMORY_REQUEST: '2Gi'
    KUBERNETES_MEMORY_LIMIT: '2Gi'

# === pre-build stage ===

#install_dependencies:
#  stage: pre-build
#  script:
#    - npm ci --cache .npm --prefer-offline
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}
#    paths:
#      - .npm/
#  artifacts:
#    expire_in: 1 day
#    paths:
#      - node_modules
#      - .svelte-kit
#  needs: []

# === build stage ===

docs:
  needs:
    - build_image_node
  stage: build
  trigger:
    include: .gitlab/docs.yml
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

# === test stage ===

unit_tests:
  needs:
    - build_image_node
  stage: test
  script:
    - cd /app
    - npx vitest run
  coverage: /All files[^|]*\|[^|]*\|\s+([\d\.]+)/
  artifacts:
    expire_in: 1 day
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  variables:
    KUBERNETES_MEMORY_REQUEST: '2Gi'
    KUBERNETES_MEMORY_LIMIT: '2Gi'

prettier:
  needs:
    - build_image_node
  stage: test
  script:
    - cd /app
    - npx prettier --check . "!misp-docker/**"
  variables:
    KUBERNETES_MEMORY_REQUEST: '2Gi'
    KUBERNETES_MEMORY_LIMIT: '2Gi'

eslint:
  needs:
    - build_image_node
  stage: test
  script:
    - cd /app
    - npx eslint --format gitlab .
  artifacts:
    expire_in: 1 day
    reports:
      codequality: gl-code-quality-report.json

svelte-check:
  allow_failure: True
  needs:
    - build_image_node
  stage: test
  script:
    - cd /app
    - npm run check

integration_tests:
  tags:
    - beefy
    - any-image-allowed
  parallel: 2
  stage: test
  image:
    name: cypress/included:14.3.3
    entrypoint: ['']
  needs:
    - build_image_node
    - build_image_nginx
  services:
    - name: registry.cert.kit.edu/public-gitlab-ci/mysql-loader:latest
      alias: db
      variables:
        MYSQL_ROOT_PASSWORD: misp
        MYSQL_DUMP_FILE: /builds/${CI_PROJECT_PATH}/misp-docker-override/dump.sql
        MYSQL_DATABASE: misp
        KUBERNETES_SERVICE_CPU_REQUEST: '100m'
        KUBERNETES_SERVICE_CPU_LIMIT: '250m'
        KUBERNETES_SERVICE_MEMORY_REQUEST: '512Mi'
        KUBERNETES_SERVICE_MEMORY_LIMIT: '512Mi'
    - name: registry.cert.kit.edu/public-gitlab-ci/misp-core:latest
      alias: misp-core
      variables:
        MYSQL_PASSWORD: misp
        MYSQL_USER: root
        DISABLE_SSL_REDIRECT: true
        ENABLE_DB_SETTINGS: 'false'
        KUBERNETES_SERVICE_CPU_REQUEST: '700m'
        KUBERNETES_SERVICE_CPU_LIMIT: '1200m'
        KUBERNETES_SERVICE_MEMORY_REQUEST: '512Mi'
        KUBERNETES_SERVICE_MEMORY_LIMIT: '512Mi'
    - name: valkey/valkey:7.2
      command: ['--requirepass 1CA9kMhX6mcuhRlRAptZdQieSX6u25SJ']
      alias: redis
      variables:
        HEALTHCHECK_TCP_PORT: 6379
        KUBERNETES_SERVICE_CPU_REQUEST: '100m'
        KUBERNETES_SERVICE_CPU_LIMIT: '200m'
        KUBERNETES_SERVICE_MEMORY_REQUEST: '128Mi'
        KUBERNETES_SERVICE_MEMORY_LIMIT: '128Mi'
    - name: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_nginx:${CI_COMMIT_SHA}
      alias: frontend
      variables:
        NGINX_PORT: 81
        PUBLIC_MAINTENANCE_MODE: 'false'
        PUBLIC_MAINTENANCE_MESSAGE: Website is currently in maintenance mode. All editing is disabled.
        PUBLIC_REST_DISABLED: '{}'
        PUBLIC_REST_DISABLED_MESSAGE: The REST method you try to use is disabled
        PUBLIC_MISP_API_ENDPOINT: https://misp-core
        PUBLIC_DATE_FORMAT: yyyy-mm-DD
        PUBLIC_COMPATIBILITY_MODE: 'true'
        KUBERNETES_SERVICE_CPU_REQUEST: '100m'
        KUBERNETES_SERVICE_CPU_LIMIT: '200m'
        KUBERNETES_SERVICE_MEMORY_REQUEST: '128Mi'
        KUBERNETES_SERVICE_MEMORY_LIMIT: '128Mi'
  script:
    # Create environment files
    - mv misp-docker-override/dump01.sql misp-docker-override/dump.sql
    - npm ci
    - npx svelte-kit sync
    - while [ ! -f "$MISP_READY_FILE" ]; do sleep 10; done
    - npx cypress run --parallel --record --ci-build-id=${CI_PIPELINE_ID}_legacy --browser chrome --reporter junit --reporter-options mochaFile=reports/report-[hash].xml
  variables:
    KUBERNETES_CPU_REQUEST: '500m'
    KUBERNETES_CPU_LIMIT: '900m'
    KUBERNETES_MEMORY_REQUEST: '1024Mi'
    KUBERNETES_MEMORY_LIMIT: '1024Mi'
    CYPRESS_BASE_URL: http://frontend:81
    CYPRESS_VIDEO: 'true'
    ELECTRON_ENABLE_LOGGING: 'true'
    REDIS_PASSWORD: 1CA9kMhX6mcuhRlRAptZdQieSX6u25SJ
    MISP_READY_FILE: '${CI_PROJECT_DIR}/misp_ready'
    CYPRESS_adminToken: '${MISP01_AUTH_TOKEN}'
    CYPRESS_legacy: 'true'
  artifacts:
    expire_in: 1 day
    reports:
      junit: reports/report-*.xml
    expose_as: Cypress artifacts
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/

integration_tests_new_api:
  tags:
    - beefy
    - any-image-allowed
  parallel: 2
  stage: test
  image:
    name: cypress/included:14.3.3
    entrypoint: ['']
  needs:
    - build_image_node
    - build_image_nginx
  services:
    - name: registry.cert.kit.edu/public-gitlab-ci/mysql-loader:latest
      alias: db
      variables:
        MYSQL_ROOT_PASSWORD: misp
        MYSQL_DUMP_FILE: /builds/${CI_PROJECT_PATH}/misp-docker-override/dump.sql
        MYSQL_DATABASE: misp
        KUBERNETES_SERVICE_CPU_REQUEST: '100m'
        KUBERNETES_SERVICE_CPU_LIMIT: '250m'
        KUBERNETES_SERVICE_MEMORY_REQUEST: '512Mi'
        KUBERNETES_SERVICE_MEMORY_LIMIT: '512Mi'
    - name: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/api:main
      alias: new-api
      variables:
        DATABASE_URL: 'mysql+aiomysql://root:misp@db:3306/misp'
        WORKER_API_KEY: OIfY8nFQ9I6okbgGZZjSkOdUUDGZbp9H
        WORKER_KEY: EU81IOLWsn8g37gK7xWToiQpUvYXdPDs
        WORKER_URL: http://worker-api:5000
        HASH_SECRET: abcdefghijklmnop
        DEBUG: true
        WORKER_COUNT: 1
        KUBERNETES_SERVICE_CPU_REQUEST: '500m'
        KUBERNETES_SERVICE_CPU_LIMIT: '700m'
        KUBERNETES_SERVICE_MEMORY_REQUEST: '512Mi'
        KUBERNETES_SERVICE_MEMORY_LIMIT: '512Mi'
    - name: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/worker:main
      alias: worker-api
      variables:
        REDIS_HOST: redis
        DB_API_URL: 'http://new-api:4000'
        API_KEY: EU81IOLWsn8g37gK7xWToiQpUvYXdPDs
        WORKER_API_KEY: OIfY8nFQ9I6okbgGZZjSkOdUUDGZbp9H
        DATABASE_URL: 'mysql+aiomysql://root:misp@db:3306/misp'
        KUBERNETES_SERVICE_CPU_REQUEST: '100m'
        KUBERNETES_SERVICE_CPU_LIMIT: '200m'
        KUBERNETES_SERVICE_MEMORY_REQUEST: '128Mi'
        KUBERNETES_SERVICE_MEMORY_LIMIT: '128Mi'
    - name: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/worker:main
      command: ['mmisp-worker']
      alias: worker
      variables:
        REDIS_HOST: redis
        DB_API_URL: 'http://new-api:4000'
        API_KEY: EU81IOLWsn8g37gK7xWToiQpUvYXdPDs
        DATABASE_URL: 'mysql+aiomysql://root:misp@db:3306/misp'
        WORKER_API_WEBSOCKET: ws://worker-api:5000/worker/ws
        WORKER_API_KEY: OIfY8nFQ9I6okbgGZZjSkOdUUDGZbp9H
        KUBERNETES_SERVICE_CPU_REQUEST: '100m'
        KUBERNETES_SERVICE_CPU_LIMIT: '200m'
        KUBERNETES_SERVICE_MEMORY_REQUEST: '512Mi'
        KUBERNETES_SERVICE_MEMORY_LIMIT: '512Mi'
    - name: valkey/valkey:7.2
      command: ['--requirepass 1CA9kMhX6mcuhRlRAptZdQieSX6u25SJ']
      alias: redis
      variables:
        HEALTHCHECK_TCP_PORT: 6379
        KUBERNETES_SERVICE_CPU_REQUEST: '50m'
        KUBERNETES_SERVICE_CPU_LIMIT: '100m'
        KUBERNETES_SERVICE_MEMORY_REQUEST: '128Mi'
        KUBERNETES_SERVICE_MEMORY_LIMIT: '128Mi'
    - name: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_nginx:${CI_COMMIT_SHA}
      alias: frontend
      variables:
        NGINX_PORT: 81
        PUBLIC_MAINTENANCE_MODE: 'false'
        PUBLIC_MAINTENANCE_MESSAGE: Website is currently in maintenance mode. All editing is disabled.
        PUBLIC_REST_DISABLED: '{}'
        PUBLIC_REST_DISABLED_MESSAGE: The REST method you try to use is disabled
        PUBLIC_MISP_API_ENDPOINT: http://new-api:4000
        PUBLIC_DATE_FORMAT: yyyy-mm-DD
        PUBLIC_COMPATIBILITY_MODE: 'false'
        KUBERNETES_SERVICE_CPU_REQUEST: '100m'
        KUBERNETES_SERVICE_CPU_LIMIT: '200m'
        KUBERNETES_SERVICE_MEMORY_REQUEST: '128Mi'
        KUBERNETES_SERVICE_MEMORY_LIMIT: '128Mi'
  script:
    # Create environment files
    - mv misp-docker-override/dump01.sql misp-docker-override/dump.sql
    - npm ci
    - npx svelte-kit sync
    - until wget -q -t1 http://new-api:4000; do rc="$?"; if [ $rc -eq 0 ] || [ $rc -eq 8 ]; then echo "MMISP API is ready"; break; else sleep 1; fi; done
    - npx cypress run --parallel --record --ci-build-id=${CI_PIPELINE_ID}_modern --browser chrome --reporter junit --reporter-options mochaFile=reports/report-[hash].xml
  variables:
    KUBERNETES_CPU_REQUEST: '700m'
    KUBERNETES_CPU_LIMIT: '1200m'
    KUBERNETES_MEMORY_REQUEST: '1024Mi'
    KUBERNETES_MEMORY_LIMIT: '1024Mi'
    CYPRESS_BASE_URL: http://frontend:81
    CYPRESS_VIDEO: 'true'
    ELECTRON_ENABLE_LOGGING: 'true'
    MISP_READY_FILE: '${CI_PROJECT_DIR}/misp_ready'
    REDIS_PASSWORD: 1CA9kMhX6mcuhRlRAptZdQieSX6u25SJ
    CYPRESS_adminToken: '${MISP01_AUTH_TOKEN}'
    CYPRESS_legacy: 'false'
    #    CI_DEBUG_SERVICES: "true"
  artifacts:
    expire_in: 1 day
    reports:
      junit: reports/report-*.xml
    expose_as: Cypress artifacts
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
