ARG fromimage
ARG fromtag
FROM $fromimage:$fromtag AS builder

RUN bun run build -- --minify false --debug --sourcemap true


FROM nginx:alpine-slim
ENV NGINX_PORT=80
COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY startup.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/startup.sh
COPY --from=builder /app/build /usr/share/nginx/html/
