#!/bin/sh

CONFIG=/usr/share/nginx/html/config.yaml

echo "---" > $CONFIG
echo "MAINTENANCE_MODE: $PUBLIC_MAINTENANCE_MODE" >> $CONFIG
echo "MAINTENANCE_MESSAGE: $PUBLIC_MAINTENANCE_MESSAGE" >> $CONFIG
echo "REST_DISABLED: $PUBLIC_REST_DISABLED" >> $CONFIG
echo "REST_DISABLED_MESSAGE: $PUBLIC_REST_DISABLED_MESSAGE" >> $CONFIG
echo "MISP_API_ENDPOINT: $PUBLIC_MISP_API_ENDPOINT" >> $CONFIG
echo "DATE_FORMAT: $PUBLIC_DATE_FORMAT" >> $CONFIG
