<script lang="ts">
  import { run } from 'svelte/legacy';

  import { goto } from '$app/navigation';
  import { api } from '$lib/api';
  import DynCard from '$lib/components/card/dynCard/DynCard.svelte';
  import Form from '$lib/components/form/Form.svelte';
  import { notifySave } from '$lib/util/notifications.util';
  import { get } from 'svelte/store';
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  import { currentRoute, appState } from '$lib/stores.svelte.ts';
  import { lockEditMode } from '$lib/actions';
  import { notifications } from '$lib/stores.svelte.ts';
  import { errorPill } from '$lib/util/pill.util';
  import { invalidateAll } from '$app/navigation';

  let { data } = $props();

  let { roles, header } = $derived(data);

  appState.mode = 'edit';

  function editCallback(formData: Record<string, string>) {
    console.log(formData);
    notifySave(
      get(api)
        .POST('/admin/users/add', {
          body: formData
        })
        .then((resp) => {
          if (resp.error) {
            // @ts-expect-error MISP API return custom errors object
            console.log(resp);
            if (resp.response.status == 406) {
              console.log('User already exists');
              notifications.add(errorPill('User already exists'));
              invalidateAll();
            }
            const mispErrors: string[] = Object.values(resp.error.errors ?? {});
            throw new Error(mispErrors.length ? mispErrors[0] : resp.error.message);
          } else {
            // Autogenerated (OpenAPI spec) type of resp.data is wrong
            goto(`/admin/users/${(resp.data as { User?: typeof resp.data })!.User!.id!}`);
          }
        })
    );
  }

  run(() => {
    $currentRoute = [
      ...($currentRoute ?? []),
      { name: 'Create a new User', href: 'new', icon: 'mdi:account-plus-outline' }
    ];
  });
</script>

<svelte:window use:lockEditMode={true} />

<!--
  @component
  Displays a form to add a new user.
-->
<Form callback={editCallback}>
  <DynCard {header} data={roles}></DynCard>
</Form>
