stages:
  - generate_docs
  - generate_uml_svg
  - generate_mkdocs

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

default:
  tags:
    - kgr1-instance-standard # Tag is required to make the CI runner accept the jobs
  image:
    name: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/frontend_node:${CI_COMMIT_SHA}

variables:
  SOURCE_DATE_EPOCH: 0
  GIT_LFS_SKIP_SMUDGE: 1

generate_docs:
  stage: generate_docs
  script:
    - cd /app
    - |
      cat << EOF > "$HOME/.bunfig.toml"
      [install.scopes]
      "@feathecutie" = "https://gitlab.com/api/v4/projects/52994631/packages/npm/"

      EOF
    - cat $HOME/.bunfig.toml
    - bunx @feathecutie/svelte-to-uml@latest . ./docs/generated
    - cp -r docs/generated $CI_PROJECT_DIR/docs
  artifacts:
    paths:
      - docs/generated
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_image_node

generate_uml_svg:
  stage: generate_uml_svg
  image:
    name: docker.io/plantuml/plantuml
    entrypoint: ['']
  script:
    - find docs -type f -name *.plantuml -exec sh -c "cat '{}' | java -Djava.awt.headless=true -jar /opt/plantuml.jar -tsvg -p > \$(dirname '{}')/\$(basename '{}' .plantuml).svg" \;
    - mv docs/sequencediagrams/plantuml/*.svg docs/sequencediagrams/svg/
  artifacts:
    paths:
      - docs

generate_mkdocs:
  stage: generate_mkdocs
  image: registry.cert.kit.edu/public-gitlab-ci/mkdocs
  script:
    - source /root/.venv/bin/activate; mkdocs build
  artifacts:
    paths:
      - site
  needs:
    - generate_uml_svg
