@startuml "Add Reference between Object and attribute in Event-Graph"
hide footbox

actor User as user
box "Frontend"
participant "Event Graph" as eventgraph
participant "Options Menu" as optmenu <<Component>>
participant "'Add Reference' Menu" as addreferencemenu <<Component>>
end box
database "Backend API" as api

activate api
activate eventgraph
note over eventgraph : Unreferenced objects/attributes displayed


user -> optmenu: click " Add Reference " button
activate optmenu

optmenu -> eventgraph: initiate "add reference" action
deactivate optmenu

eventgraph -> user: allow dragging an edge from node to node

user -> eventgraph: drag new reference from an object to an attribute

eventgraph -> addreferencemenu: initiate "enter attribute values" action


activate addreferencemenu
note over addreferencemenu: Reference menu displayed

addreferencemenu --> user:input form for attributes of new reference

user -> addreferencemenu: submit filled form

addreferencemenu -> api: send save request

api --> addreferencemenu: success
deactivate addreferencemenu

eventgraph -> eventgraph: add newly added edge

note over eventgraph : New reference added

@enduml
