@startuml "Add Event"
hide footbox

actor User as user
box "Frontend"
participant "Event List" as eventlist
participant "Create Event Dialogue" as createdialogue
participant TopMenu as topmenu <<Component>>
participant Layout as layout <<Component>>
end box
database "Backend API" as api

note over eventlist : event list is displayed

activate eventlist
user -> topmenu : toggle edit mode
topmenu --> layout : state changes
layout -> eventlist : enter edit mode
user -> topmenu : click "add event"
topmenu --> layout : state changes
layout -> createdialogue : open "create event" dialogue
activate createdialogue
note left : editable values form inputs
user -> createdialogue : change input value
createdialogue --> createdialogue : update internal value

user -> createdialogue : click save
createdialogue -> api : PATCH event
api --> createdialogue : success
deactivate eventlist
createdialogue --> user : redirect to /event/[id]
createdialogue -> layout : exit edit mode
layout -> topmenu : view mode
deactivate createdialogue

@enduml
